apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: application-pipeline
spec:
  resources:
    - name: source
      type: git
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: .
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: config.yaml
    - name: imageUrl
      description: Url of image repository
      default: us.icr.io/living-on-the-cloud/sampleapp
    - name: imageTag
      description: Tag to apply to the built image
      default: latest
  tasks:
  - name: build-image-from-source
    taskRef:
      name: build-image-from-source
    params:
      - name: pathToContext
        value: "$(params.pathToContext)"
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: source
          resource: source
  - name: deploy-application
    taskRef:
      name: deploy-application
    runAfter:
      - build-image-from-source
    params:
      - name: pathToContext
        value: "$(params.pathToContext)"
      - name: pathToYamlFile
        value: "$(params.pathToYamlFile)"
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: source
          resource: source
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: sampleapp
spec:
  serviceAccountName: sampleapp
  triggers:
  - name: pullrequest-build-and-deploy
    template:
      name: sampleapp-build-and-deploy
    bindings:
    - name: sampleapp-build-and-deploy
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: sampleapp-build-and-deploy
spec:
  params:
  - name: URL
    value: $(body.repository.clone_url)
  - name: REVISION
    value: $(body.pull_request.head.sha)
  - name: NAMESPACE
    value: living-on-the-cloud
  - name: DEPLOYMENT
    value: sampleapp
  - name: SERVICE_ACCOUNT
    value: service-account
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: sampleapp-build-and-deploy
spec:
  params:
  - name: URL
    description: The repository url to build and deploy.
  - name: REVISION
    description: The revision to build and deploy.
  - name: NAMESPACE
    description: The namespace is used by OpenShift's internal image registry to store the built image.
  - name: DEPLOYMENT
    description: Name of the Deployment and the container name in the Deployment.
  - name: SERVICE_ACCOUNT
    description: The ServiceAccount under which to run the Pipeline.
  - name: API-KEY
    description: The API-KEY
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: sample-build-and-deploy-
    spec:
      serviceAccountName: $(params.SERVICE_ACCOUNT)
      pipelineRef:
        name: application-pipeline
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(params.REVISION)
          - name: url
            value: $(params.URL)
      params:
      - name: DEPLOYMENT
        value: $(params.DEPLOYMENT)
  - apiVersion: v1
    stringData:
      username: iamapikey
      password: $(params.API-KEY)
    kind: Secret
    type: kubernetes.io/basic-auth
    metadata:
      name: ibm-cr-secret
      annotations:
        tekton.dev/docker-0: us.icr.io
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image-from-source
spec:
  resources:
    inputs:
      - name: source
        type: git
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: /workspace/source
    - name: pathToDockerfile
      description: The path to the dockerfile to build
      default: Dockerfile
    - name: imageUrl
      description: value should be like - us.icr.io/test_namespace/builtImageApp
    - name: imageTag
      description: Tag to apply to the built image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - "--dockerfile=$(params.pathToDockerfile)"
        - "--destination=$(params.imageUrl):$(params.imageTag)"
        - "--context=$(params.pathToContext)"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-application
spec:
  resources:
    inputs:
      - name: source
        type: git
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: /src/
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: deploy.yaml
    - name: imageUrl
      description: Url of image repository
      default: url
    - name: imageTag
      description: Tag of the images to be used.
      default: "latest"
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;IMAGE;$(params.imageUrl):$(params.imageTag);g"
        - "$(resources.inputs.source.path)/$(params.pathToContext)/$(params.pathToYamlFile)"
    - name: deploy-app
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(resources.inputs.source.path)/$(inputs.params.pathToContext)/$(params.pathToYamlFile)"
		
