apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
  annotations:
	test-annotation: $(params.TEST-VALUE)
secrets:
- name: ibm-cr-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: kube-api-secret
  annotations:
    kubernetes.io/service-account.name: service-account
	tekton.dev/docker-0: us.icr.io
type: kubernetes.io/service-account-token

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pipeline-role
  annotations:
	test-annotation: $(params.TEST-VALUE)
rules:
- apiGroups: ["extensions", "apps", ""]
  resources: ["services", "deployments", "pods"]
  verbs: ["get", "create", "update", "patch", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: service-account
  namespace: default

---

apiVersion: v1
stringData:
  username: iamapikey
  password: {{API-KEY}}
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: ibm-cr-secret
  annotations:
    tekton.dev/docker-0: us.icr.io