apiVersion: v1
kind: Service
metadata:
  name: sampleapp
  labels:
    sampleapp: sampleapp
spec:
  type: NodePort
  ports:
    - port: 3300
      name: sampleapp
      nodePort: 32426
  selector:
    sampleapp: sampleapp
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    sampleapp: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      sampleapp: sampleapp
  template:
    metadata:
      labels:
        sampleapp: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: IMAGE
        ports:
        - containerPort: 3300
