apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-application
spec:
  resources:
    inputs:
      - name: source
        type: git
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: .
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: deploy.yaml
    - name: imageUrl
      description: Url of image repository
      default: url
    - name: imageTag
      description: Tag of the images to be used.
      default: "latest"
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;IMAGE;$(params.imageUrl):$(params.imageTag);g"
        - "$(resources.inputs.source.path)/$(params.pathToContext)/$(params.pathToYamlFile)"
    - name: deploy-app
      image: ibmcom/pipeline-base-image
      env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: secure-properties
              key: API-KEY
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          ibmcloud login -a cloud.ibm.com -r us-south --apikey $APIKEY;
          export IKS_BETA_VERSION=1;
          ibmcloud ks cluster config -c "mycluster";
          kubectl apply -f $(resources.inputs.source.path)/$(inputs.params.pathToContext)/$(params.pathToYamlFile);